SELECT * FROM TB_PEDIDO
SELECT * FROM TB_DETALHE_PEDIDO
SELECT * FROM TB_CLIENTE

SELECT 
  TOP 5
  CL.NomeCompleto AS NOME_CLIENTE,
  SUM((DE.Quantidade * DE.Preco) - DE.Desconto)  [VALOR_TOTAL_EM_COMPRAS]
FROM 
	TB_PEDIDO AS PE
INNER JOIN TB_DETALHE_PEDIDO AS DE ON DE.NumeroPedido = PE.NumeroPedido
INNER JOIN TB_CLIENTE AS CL ON CL.ClienteId = PE.ClienteId
GROUP BY
	CL.NomeCompleto
ORDER BY 
	[VALOR_TOTAL_EM_COMPRAS] DESC


SELECT 
  PE.NumeroPedido AS NUMERO_PEDIDO,
  CL.NomeCompleto AS NOME_CLIENTE,
  AVG(DE.Preco * DE.Quantidade) AS [MEDIA_POR_USUARIO]
FROM 
	TB_PEDIDO AS PE
INNER JOIN TB_DETALHE_PEDIDO AS DE ON DE.NumeroPedido = PE.NumeroPedido
INNER JOIN TB_CLIENTE AS CL ON CL.ClienteId = PE.ClienteId
GROUP BY
	CL.NomeCompleto, PE.NumeroPedido

SELECT 
  TOP 10
  PR.ProdutoId AS ID_PRODUTO,
  PR.Descricao AS PRODUTO,
  SUM(DE.Quantidade) AS QUANTIDADE_PRODUTOS_VENDIDOS
FROM 
	TB_PEDIDO AS PE 
INNER JOIN TB_DETALHE_PEDIDO AS DE  ON DE.NumeroPedido = PE.NumeroPedido
INNER JOIN TB_PRODUTO AS PR ON PR.ProdutoId = DE.ProdutoId
GROUP BY
  PR.ProdutoId, PR.Descricao
ORDER BY 
  QUANTIDADE_PRODUTOS_VENDIDOS DESC
