

--MULTIPLOS ARQUIVOS DE BACKUP
USE MASTER
GO
DROP DATABASE AULA_BKP

--CRIANDO DATABASE
CREATE DATABASE AULA_BKP
USE AULA_BKP

CREATE TABLE Registros(
	ID_REGISTRO INT IDENTITY(1,1) PRIMARY KEY,
	CARGA VARCHAR(50)
);

---INSERT INTO Registros VALUES ('1 CARGA') GO 1000000

CREATE PROCEDURE PROC_CARGA(@QTD_INSERT INT) 
AS 
DECLARE 
@HORA_INI AS DATETIME,
@HORA_FIM AS DATETIME,
@QTD_COMMIT AS INT,
@CONTADOR AS INT,
@DURACAO AS INT
BEGIN
BEGIN TRANSACTION 
	SET @CONTADOR =0;
	SET @QTD_COMMIT=0;
	SET @HORA_INI = GETDATE();
	SELECT 'HORA INICIO' +CAST(@HORA_INI AS VARCHAR(50))

	WHILE @CONTADOR < @QTD_INSERT
		BEGIN 
		INSERT INTO Registros VALUES ('1 CARGA');

		SET @CONTADOR +=1;
		SET @QTD_COMMIT+=1;
		IF @QTD_COMMIT = 1000 BEGIN
			SET @QTD_COMMIT =0
			COMMIT;
			BEGIN TRANSACTION 
		END
	END
	COMMIT 
		SET @HORA_FIM = GETDATE()
		SELECT 'HORA FIM' +CAST(@HORA_INI AS VARCHAR(50))
		SET @DURACAO = DATEDIFF(SECOND,@HORA_FIM,@HORA_INI)
		SELECT 'DURACAO' +CAST(@DURACAO AS VARCHAR(50))	+ ' Segs'
	END

EXEC PROC_CARGA 1000000

SELECT COUNT(*) FROM REGISTROS
SELECT @@TRANCOUNT

--BACKUP MULTIPLOS, FULL
BACKUP DATABASE AULA_BKP
TO DISK = 'C:\SQL\ARQUIVO_BACKUP_FULL01_10_06_26.BAK',
   DISK = 'C:\SQL\ARQUIVO_BACKUP_FULL02_10_06_26.BAK',
   DISK = 'C:\SQL\ARQUIVO_BACKUP_FULL03_10_06_26.BAK'
   WITH STATS
-- BACKUP DE LOG
BACKUP LOG AULA_BKP TO DISK = 'C:\SQL\ARQUIVO_BACKUP_LOG9103_10_06_26.TRN'
-- RESTORE MULTIPLOS

USE MASTER
GO
RESTORE DATABASE AULA_BKP
FROM DISK = 'C:\SQL\ARQUIVO_BACKUP_FULL01_10_06_26.BAK',
   DISK = 'C:\SQL\ARQUIVO_BACKUP_FULL02_10_06_26.BAK',
   DISK = 'C:\SQL\ARQUIVO_BACKUP_FULL03_10_06_26.BAK'
   WITH STATS,REPLACE,NORECOVERY
--COLOCANDO NO AR 
USE MASTER
RESTORE DATABASE AULA_BKP WITH RECOVERY