
DROP DATABASE AULA_BKP

USE MASTER 

CREATE DATABASE AULA_BKP ON PRIMARY
(
	NAME = N'AULA_BK1', FILENAME='C:\SQL\AULA_BK1.MDF',
	SIZE =4288KB,MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB
), FILEGROUP AULA
(
	NAME = N'AULA_BK2', FILENAME='C:\SQL\AULA_BK2.NDF',
	SIZE =4288KB,MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB
)
LOG ON
(
	NAME = N'AULA_BK_log', FILENAME='C:\SQL\AULA_BK_log.ldf',
	SIZE =1072KB,MAXSIZE = 2048MB, FILEGROWTH = 10%
)


--- alterando para modo recovery full
ALTER DATABASE AULA_BKP SET RECOVERY FULL

--BACKUP
BACKUP DATABASE AULA_BKP TO DISK ='C:\SQL\AULA_BKP_FULL_05_06_26.BAK'
GO

USE  AULA_BKP
CREATE TABLE Registros (
	id_registro int identity(1,1) primary key,
	carga varchar(50)
) on AULA
GO
INSERT INTO REGISTROS VALUES ('1 CARGA') 
GO 1000

ALTER DATABASE AULA_BKP
ADD FILE (
	NAME = N'AULA_BK4', FILENAME='C:\SQL\AULA_BK4.NDF',
	SIZE =4288KB,MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB
) TO FILEGROUP AULA

SELECT COUNT(*) FROM REGISTROS

--CRIANDO BACKUP COM ARQUIVO DE LOG
BACKUP LOG AULA_BKP TO DISK = 'C:\SQL\AULA_BK_LOG1.TRN'

--SEGUNDA CARGA
INSERT INTO REGISTROS VALUES ('2 CARGA') 
GO 1000


--CRIANDO BACKUP COM ARQUIVO DE LOG
BACKUP LOG AULA_BKP TO DISK = 'C:\SQL\AULA_BK_LOG2.TRN'


--TERCEIRA CARGA
INSERT INTO REGISTROS VALUES ('3 CARGA') 
GO 1000


--CRIANDO BACKUP COM ARQUIVO DE LOG
BACKUP LOG AULA_BKP TO DISK = 'C:\SQL\AULA_BK_LOG3.TRN'


--RECOPERANDO DADOS COM BACKUP FULL PRIMEIRO
RESTORE DATABASE AULA_BKP FROM DISK ='C:\SQL\AULA_BKP_FULL_05_06_26.BAK'
WITH STANDBY = N'C:\SQL\AULA_BK_ROLLBACKUNDO_0.BAK', STATS 
GO


--RECOPERANDO DADOS COM BACKUP DE LOG 1 DE 3 
RESTORE DATABASE AULA_BKP FROM DISK ='C:\SQL\AULA_BK_LOG1.TRN'
WITH STANDBY = N'C:\SQL\AULA_BK_ROLLBACKUNDO_1.BAK', STATS 


--RECOPERANDO DADOS COM BACKUP DE LOG 2 DE 3 
RESTORE DATABASE AULA_BKP FROM DISK ='C:\SQL\AULA_BK_LOG2.TRN'
WITH STANDBY = N'C:\SQL\AULA_BK_ROLLBACKUNDO_2.BAK', STATS 


--RECOPERANDO DADOS COM BACKUP DE LOG 3 DE 3 
RESTORE DATABASE AULA_BKP FROM DISK ='C:\SQL\AULA_BK_LOG3.TRN'
WITH STANDBY = N'C:\SQL\AULA_BK_ROLLBACKUNDO_3.BAK', STATS 


USE MASTER
GO 
RESTORE DATABASE AULA_BKP WITH RECOVERY