-- CRIANDO BANCO
USE MASTER
CREATE DATABASE AULA_BKP ON PRIMARY
(
	NAME = N'AULA_BK1', FILENAME='C:\SQL\AULA_BK1.MDF',
	SIZE =4288KB,MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB
), FILEGROUP AULA
(
	NAME = N'AULA_BK2', FILENAME='C:\SQL\AULA_BK2.NDF',
	SIZE =4288KB,MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB
)
LOG ON
(
	NAME = N'AULA_BK_log', FILENAME='C:\SQL\AULA_BK_log.ldf',
	SIZE =1072KB,MAXSIZE = 2048MB, FILEGROWTH = 10%
)

--ALTERANDO MODO DE RECUPERACAO
ALTER DATABASE AULA_BKP SET RECOVERY FULL

--BACKUP
BACKUP DATABASE AULA_BKP TO DISK ='C:\SQL\AULA_BKP_FULL_09_06_26.BAK' WITH STATS 
GO
--CRIANDO TABELA
USE  AULA_BKP
CREATE TABLE Registros (
	id_registro int identity(1,1) primary key,
	carga varchar(50)
) on AULA

--1  CARGA
INSERT INTO REGISTROS VALUES ('1 CARGA') 

GO 1000
--- BACKUP DIFERENCIAL 
BACKUP DATABASE AULA_BKP TO DISK ='C:\SQL\AULA_BKP_DIFF1_09_06_26.BAK' WITH DIFFERENTIAL 
GO

--2  CARGA
INSERT INTO REGISTROS VALUES ('2 CARGA') 
--- BACKUP DIFERENCIAL 
BACKUP DATABASE AULA_BKP TO DISK ='C:\SQL\AULA_BKP_DIFF2_09_06_26.BAK' WITH DIFFERENTIAL 
GO

--3  CARGA
INSERT INTO REGISTROS VALUES ('3 CARGA') 
--- BACKUP DIFERENCIAL 
BACKUP DATABASE AULA_BKP TO DISK ='C:\SQL\AULA_BKP_DIFF3_09_06_26.BAK' WITH DIFFERENTIAL 
GO

--DELETANDO REGISTROS DA TABELA
USE AULA_BKP
DELETE FROM REGISTROS


--Verifica as marcas de LSN do segundo Backup full
--numeros de sequencia de log = LSN
--MOSTRA QUANDO FEZ, QUAL BANCO E ETC
RESTORE HEADERONLY FROM DISK ='C:\SQL\AULA_BKP_FULL_09_06_26.BAK'
RESTORE HEADERONLY FROM DISK ='C:\SQL\AULA_BKP_DIFF1_09_06_26.BAK'
RESTORE HEADERONLY FROM DISK ='C:\SQL\AULA_BKP_DIFF2_09_06_26.BAK'
RESTORE HEADERONLY FROM DISK ='C:\SQL\AULA_BKP_DIFF3_09_06_26.BAK'

--RESTAURAR BACKUP FULL

USE MASTER
GO

-- BACKUP LOG
BACKUP LOG AULA_BKP TO DISK= 'C:\SQL\AULA_BKP_LOG1.TRN'

--RESTAURAR BACKUP FULL
RESTORE DATABASE AULA_BKP FROM DISK ='C:\SQL\AULA_BKP_FULL_09_06_26.BAK' WITH NORECOVERY,REPLACE, STATS
GO

--RESTAURAR DIFF 3 (ULTIMO BACKUP DIFERENCIAL)
RESTORE DATABASE AULA_BKP FROM DISK ='C:\SQL\AULA_BKP_DIFF3_09_06_26.BAK' WITH NORECOVERY,REPLACE, STATS
GO

USE MASTER
--DEIXANDO ACESSIVEL
RESTORE DATABASE AULA_BKP WITH RECOVERY 


USE AULA_BKP
SELECT COUNT(*) FROM REGISTROS